certmanager:
  install: false
gitlab-runner:
  runners:
    privileged: true
global:
  appConfig:
    artifacts:
      bucket: gitlab-artifacts-platform-tools-dev
    dependencyProxy:
      bucket: gitlab-dependencyproxy-storage-platform-tools-dev
    externalDiffs:
      bucket: gitlab-externaldiffs-storage-platform-tools-dev
    lfs:
      bucket: gitlab-lfs-storage-platform-tools-dev
    packages:
      bucket: gitlab-packages-storage-platform-tools-dev
    terraformState:
      bucket: gitlab-terraform-state-platform-tools-dev
    uploads:
      bucket: gitlab-uploads-storage-platform-tools-dev
  hosts:
    domain: gitlab.xxx.com
  ingress:
    configureCertmanager: false
  psql:
    database: postgres
    host: database-1.xxxxxxxxxx.rds.amazonaws.com
    password:
      key: postgresql-password
      secret: gitlab-postgresql-password
    port: 5432
    username: postgres
  redis:
    host: rxxxxxxxxxcache.amazonaws.com
    password:
      enabled: false
    port: 6379
  certificates:
    image:
      repository: xxxxxxxxxx.dkr..amazonaws.com/alpine-certificates
      tag: 20171114-r3
  kubectl:
    image:
      repository: xxxxxxxxxx.dkr..amazonaws.com/kubectl
      tag: 1.13.12
  busybox:
    image:
      repository: xxxxxxxxxx.dkr..amazonaws.com/busybox
      tag: latest
nginx-ingress:
  controller:
    service:
      annotations:
        service.beta.kubernetes.io/aws-load-balancer-internal: true
postgresql:
  install: false
redis:
  install: false
minio:
  image: xxxxxxxxxx.dkr..amazonaws.com/minio/minio
  imageTag: "RELEASE.2017-12-28T01-21-00Z"
  minioMc:
    image: xxxxxxxxxx.dkr..amazonaws.com/minio/mc
    tag: "RELEASE.2018-07-13T00-53-22Z"
nginx-ingress:
  controller:
  image:
    repository: xxxxxxxxxx.dkr..amazonaws.com/quay.io/kubernetes-ingress-controller/nginx-ingress-controller
    tag: "0.21.0"
  defaultBackend:
  image:
    repository: xxxxxxxxxx.dkr..amazonaws.com/k8s.gcr.io/defaultbackend
    tag: "1.4"
registry:
  image:
    repository: xxxxxxxxxx.dkr..amazonaws.com/gitlab-container-registry
    tag: "v2.11.0-gitlab"
shared-secrets:
  selfsign:
    image:
      repository: xxxxxxxxxx.dkr..amazonaws.com/cfssl-self-sign
      tag: "1.2"
gitlab:
  global:
    enterpriseImages:
      migrations:
        repository: xxxxxxxxxx.dkr..amazonaws.com/gitlab-task-runner-ee
      sidekiq:
        repository: xxxxxxxxxx.dkr..amazonaws.com/gitlab-sidekiq-ee
      task-runner:
        repository: xxxxxxxxxx.dkr..amazonaws.com/gitlab-task-runner-ee
      webservice:
        repository: xxxxxxxxxx.dkr..amazonaws.com/gitlab-webservice-ee
      workhorse:
        repository: xxxxxxxxxx.dkr..amazonaws.com/gitlab-workhorse-ee
      geo-logcursor:
        repository: xxxxxxxxxx.dkr..amazonaws.com/gitlab-geo-logcursor
  gitlab-shell:
    image:
      repository: xxxxxxxxxx.dkr..amazonaws.com/gitlab-shell
      tag: "v13.11.0"
  gitaly:
    image:
      repository: xxxxxxxxxx.dkr..amazonaws.com/gitaly
      tag: "v13.5.3"
  gitlab-exporter:
    image:
      repository: xxxxxxxxxx.dkr..amazonaws.com/gitlab-exporter
      tag: "7.0.6"
  gitlab-shell:
    image:
      repository: xxxxxxxxxx.dkr..amazonaws.com/gitlab-shell
      tag: "v13.11.0"
  kas:
    image:
      repository: xxxxxxxxxx.dkr..amazonaws.com/cluster-integration/gitlab-agent/kas
      tag: "v0.0.6"
  mailroom:
    image:
      repository: xxxxxxxxxx.dkr..amazonaws.com/gitlab-mailroom
      tag: "0.0.7"
  operator:
    image:
      repository: xxxxxxxxxx.dkr..amazonaws.com/gitlab-operator
      tag: "latest"
  praefect:
    image:
      repository: xxxxxxxxxx.dkr..amazonaws.com/gitaly
      tag: "v13.5.3"



  



         

